site_name: AWS FSx Lifecycle Status Monitor
site_description: 'Documentation for the AWS FSx Lifecycle Status Monitor'
site_author: 'Stefan Freitag'
docs_dir: docs/
repo_name: 'stefanfreitag/AWS-FSx-Lifecycle-Status-Monitor'
repo_url: 'https://github.com/stefanfreitag/AWS-FSx-Lifecycle-Status-Monitor'
edit_uri: blob/main/docs/
nav:
    - Home: index.md
    - Architecture: architecture.md
    - Usage: usage.md
    - Links: links.md
theme:
  name: 'material'
  palette:
    scheme: default

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences